spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/academic_events_db}
    username: ${DB_USERNAME:ups}
    password: ${DB_PASSWORD:ups123}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  flyway:
    enabled: true 

logging:
  level:
    ec.edu.ups.academicevents: DEBUG