package ec.edu.ups.academicevents.shared.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    RESOURCE_NOT_FOUND,
    DUPLICATE_RESOURCE,
    BUSINESS_RULE_VIOLATION,
    ACCESS_DENIED,
    INVALID_TOKEN,
    RATE_LIMIT_EXCEEDED,
    INTERNAL_ERROR,
    INVALID_CREDENTIALS,
    TOKEN_EXPIRED,
    ACCOUNT_BLOCKED,
    NOT_RESOURCE_OWNER,

    // --- Inscripciones ---
    ALREADY_REGISTERED,
    NO_CAPACITY,
    EVENT_NOT_OPEN,
    EVENT_FINISHED,
    REGISTRATION_WINDOW_CLOSED,
    INVALID_STATE_TRANSITION,
    CONCURRENT_UPDATE,

    // --- Eventos ---
    EVENT_HAS_REGISTRATIONS
}
