package ec.edu.ups.academicevents.shared.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    RESOURCE_NOT_FOUND,
    DUPLICATE_RESOURCE,
    BUSINESS_RULE_VIOLATION,
    ACCESS_DENIED,
    INVALID_TOKEN,
    RATE_LIMIT_EXCEEDED,
    INTERNAL_ERROR,
    INVALID_CREDENTIALS,
    TOKEN_EXPIRED,
    ACCOUNT_BLOCKED,
    NOT_RESOURCE_OWNER
}
